name: Build and Artifact Upload

on:
  push:
    branches:
      - '**'

jobs:
  lint-format:
    name: Linting and Formatting Checks
    uses: ./.github/workflows/lint-and-format.yml

  build:
    needs: lint-format
    name: Build
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU for ARM64
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker container
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URI: ${{ secrets.REDIS_URI }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_DRIVE_LINK: ${{ secrets.NEXT_PUBLIC_DRIVE_LINK }}
          PRODUCTION_BUILD: 'true'
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max \
            --secret id=DATABASE_URL \
            --secret id=REDIS_URI \
            --secret id=NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY \
            --secret id=NEXT_PUBLIC_DRIVE_LINK \
            --platform=linux/arm64 --file=Dockerfile -t csclub-website .
            --output type=tar,dest=csclub-website.tar.gz \
          gzip csclub-website.tar.gz

      - name: Save Docker cache
        if: success()
        run: |
          rsync -a --delete /tmp/.buildx-cache-new/ /tmp/.buildx-cache/

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: csclub-website-image
          path: csclub-website.tar.gz
